version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_universidade
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=universidade_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net-universidade

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_universidade
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=estevao@estevao.com
      - PGADMIN_DEFAULT_PASSWORD=estevao
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - net-universidade

volumes:
  postgres_data:

networks:
  net-universidade:
    driver: bridge
